import { Inter } from "next/font/google";
import "./globals.css";
import TestBranch from "./TestBranch";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "TEST Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={inter.className}>
            {children}
            <TestBranch />
            <footer className="bg-red-200">TEST</footer>
         </body>
      </html>
   );
}
